version: "3"

networks:
  asvsp:
    name: asvsp
    external: true

services:
  namenode:
    #image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    build: .
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./data:/data
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - .env
    networks:
      - asvsp

  datanode1:
    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - .env
    networks:
      - asvsp

  datanode2:
    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - .env
    networks:
      - asvsp

 
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
