# DEPRECATED: This Dockerfile is no longer used after migration to apache/spark:3.5.8-java17-python3
# The official Apache image handles classpath configuration automatically.
# Keeping this file for reference only.

#FROM bde2020/spark-master:3.0.1-hadoop3.2
# FROM bitnamilegacy/spark:latest

#RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/' >> /spark/bin/load-spark-env.sh
# RUN echo 'export SPARK_CLASSPATH=$SPARK_HOME/jars/*' >> conf/spark-env.sh
# RUN echo 'export HADOOP_CLASSPATH=$SPARK_HOME/jars/*' >> conf/spark-env.sh

